language: php
php:
  - 5.4
  - 5.5
  - 5.6
install:
  - composer install
  - ./vendor/bin/codecept build
script:
  - ./vendor/bin/codecept run
branches:
  only:
    - master
# FIXME
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE testdb; USE testdb; CREATE TABLE comments (id INT PRIMARY KEY, content VARCHAR(255), user_id INT);'
# END FIXME
